name: nuiou
favicon: null
layout_spectrum: 1
typography_spectrum: 0.97185
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#06101c'
    - '#f2ebd2'
    - '#d4c89e'
    - '#93a493'
    - '#4f6f77'
  brandStrength: 0.3125
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.9199077081866562
purpose: []
