name: nuiou
favicon: null
layout_spectrum: 1
typography_spectrum: 0.97185
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.032551027135923505
  lightness: 0.8672827060800046
  saturation: 0.7992016018833965
  rhythmicContrast: 0.9199077081866562
purpose: []
